### ISSUE TITLE
Metric error when running on Ticket Dataset

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [mahmoodm2/tableGAN#5]
I've been trying to run tableGAN on the tickets dataset. For this, I transformed all categorical data to numbers and used the flight destination as label for the classifier. However, when running the model i get the following error: 

```
Traceback (most recent call last):
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: d
         [[{{node d}} = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](d/tag, discriminator/Sigmoid)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 206, in <module>
    tf.app.run()
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 185, in main
    tablegan.train(FLAGS)
  File "C:\Users\C64062\Documents\tableGAN\model.py", line 417, in train
    self.y_normal : batch_labels_normal
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: d
         [[node d (defined at C:\Users\C64062\Documents\tableGAN\model.py:185)  = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](d/tag, discriminator/Sigmoid)]]

Caused by op 'd', defined at:
  File "main.py", line 206, in <module>
    tf.app.run()
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 178, in main
    test_id=FLAGS.test_id
  File "C:\Users\C64062\Documents\tableGAN\model.py", line 116, in __init__
    self.build_model()
  File "C:\Users\C64062\Documents\tableGAN\model.py", line 185, in build_model
    self.d_sum = histogram_summary("d", self.D)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\summary\summary.py", line 187, in histogram
    tag=tag, values=values, name=scope)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 283, in histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\C64062\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: d
         [[node d (defined at C:\Users\C64062\Documents\tableGAN\model.py:185)  = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](d/tag, discriminator/Sigmoid)]]
```

saying a histogram value is None. However, I'm not familiar enough with tensorflow to debug this problem. Any thoughts on what causes this issue?

**Comment by Baukebrenninkmeijer** [comment]
Seems to be my own fault. My apologies.
