### ISSUE TITLE
How to run tableGAN with Ticket_100k dataset ?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [mahmoodm2/tableGAN#7]
As the title, I want to know how to run tableGAN with `Ticket_100k.csv` in `Music`?
Because `Ticket_100k` includes categorical data, not like Adult (only number data), which helpful for my problem.

**Comment by Baukebrenninkmeijer** [comment]
In the notebook in this repo there is a function and an example using the Ticket data as to how you convert the values easily to work with this gan. Just open the notebook with Jupyter and it should be easily explained.

**Comment by TrinhDinhPhuc** [comment]
Great, I will look it up. If there is no problem with it I will close this issue myself. Hope that in the meanwhile you will not disappear on Github :)

**Comment by soft-nougat** [comment]
Hey Trinh! Thanks for opening this up. Can you share your insights when you are done perhaps? :)))

**Comment by TrinhDinhPhuc** [comment]
@soft-nougat I haven't done yet. @Baukebrenninkmeijer I faced this issue, could you help me.
```
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 152, in main
    test_id=FLAGS.test_id
  File "/media/harry/harry/ML/tableGAN/model.py", line 108, in __init__
    self.data_X, self.data_y, self.data_y_normal = self.load_dataset(is_shadow_gan)
  File "/media/harry/harry/ML/tableGAN/model.py", line 808, in load_dataset
    return self.load_tabular_data(self.dataset_name, self.input_height, self.y_dim, self.test_id, load_fake_data)
  File "/media/harry/harry/ML/tableGAN/model.py", line 858, in load_tabular_data
    y_onehot[i, y[i]] = 1.0
IndexError: index 2 is out of bounds for axis 1 with size 2
```

**Comment by Baukebrenninkmeijer** [comment]
@TrinhDinhPhuc  I'm gonna guess you have more than two classes in your labels but your y_dim is set to 2. Please verify whether these values correspond to each other.
